#!/bin/bash

echo "=== Checking Redis on Production Server ==="
echo ""
echo "Run these commands on your server:"
echo ""
echo "Option 1: SSH and check manually:"
echo "----------------------------------------"
echo "ssh user@your-server-ip"
echo ""
echo "# Then run these commands:"
echo "redis-cli ping                    # Should return PONG if running"
echo "redis-server --version            # Shows version if installed"
echo "sudo systemctl status redis       # Check service status"
echo "ps aux | grep redis              # Check if process running"
echo ""
echo "Option 2: Quick remote check:"
echo "----------------------------------------"
echo 'ssh user@your-server-ip "redis-cli ping && echo Redis is running || echo Redis not found"'
echo ""
echo "=== If Redis is NOT installed, here's how to install it: ==="
echo ""
echo "# Connect to your server"
echo "ssh user@your-server-ip"
echo ""
echo "# Install Redis"
echo "sudo apt update"
echo "sudo apt install redis-server -y"
echo ""
echo "# Configure Redis for production"
echo "sudo nano /etc/redis/redis.conf"
echo "# Set: maxmemory 256mb"
echo "# Set: maxmemory-policy allkeys-lru"
echo ""
echo "# Start and enable Redis"
echo "sudo systemctl start redis-server"
echo "sudo systemctl enable redis-server"
echo ""
echo "# Test Redis"
echo "redis-cli ping"
echo "# Should return: PONG"
echo ""
echo "# Check memory usage"
echo "redis-cli INFO memory | grep used_memory_human"