#!/bin/bash

echo "=== Checking Live Server Code ==="
echo ""
echo "Run these commands on your server to check what's been fixed:"
echo ""
echo "cd /var/www/softeefi/backend"
echo ""
echo "# 1. Check JWT secret variables"
echo "grep 'process.env.SECRET\\|process.env.JWT_SECRET' middleware/requireAuth.js middleware/requireAdmin.js"
echo ""
echo "# 2. Check if admin protection added to free-reports"
echo "grep -A2 'router.get.*users' routes/freeReports.js"
echo ""
echo "# 3. Check what's cached in server.js"
echo "grep 'cacheMiddleware' server.js"
echo ""
echo "# 4. Check Redis usage"
echo "redis-cli KEYS '*' | head -10"
echo ""
echo "# 5. Check current server.js routes"
echo "grep 'app.use.*api' server.js"
echo ""
echo "# 6. Check if AI routes are active"
echo "grep -E '^[^/]*app.use.*ai|^[^/]*app.use.*gemini' server.js"